### ISSUE TITLE
Futures Rest Api throws errors on placing STOP or TAKE_PROFIT or  STOP_MARKET or LIMIT orders

### ISSUE THREAD

**Issue by djangoengine** [oliver-zehentleitner/unicorn-binance-rest-api#14]
Hi Oliver, 
Thanks for your prompt response on UBWA, 
I quickly looked up your rest-API which is similar to python-binance.
I was using the futures_create_order method to place STOP order or TAKE_PROFIT  as order type to modify positions.

I have been through Binance futures documentation at [https://binance-docs.github.io/apidocs/futures/en/#new-order-trade](url) 
provided all required mandatory parameters However which ever way I modify the code, it throws errors.

Have you had this kind of issue?

`   binance.exceptions.BinanceAPIException: APIError(code=-1102): A mandatory parameter was not sent, was empty/null, or malformed.  `

`                                             traded_order=self.client.futures_create_order(symbol= self.symbol, \
						# newClientOrderId=clientorderId,
						side= "BUY",  
						positionSide= "LONG",           
						# timeInForce= 'GTC', \
						quantity= qty,\
						type="TAKE_PROFIT",
						
						# price= price ,\  not mandatory
					
						stopPrice= price, \
						workingType= 'MARK_PRICE',  
					
						priceProtect='TRUE',\
						timeInForce='GTC',
						# callbackRate= 'float' ,\
						# activationPrice= 'float', \
							
						newOrderRespType= 'ACK',\
						timestamp=timestamp

						
		)`

**Comment by djangoengine** [comment]
Solved the issue, was not using price as manadatory parameter

**Comment by oliver-zehentleitner** [comment]
I have seen `A mandatory parameter was not sent, was empty/null, or malformed. ` so many times :D

Its a response from Binance and is allways related to submitted parameters....
