### ISSUE TITLE
cancel all orders for a symbol

### ISSUE THREAD

**Issue by mfurlend** [oliver-zehentleitner/unicorn-binance-rest-api#3]
**Is your feature request related to a problem? Please describe.**
I am trying to minimize the number of calls that I make to the binance REST API. One of the actions that I frequently take is to cancel all orders for a symbol. I see that binance implements this endpoint: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#cancel-all-open-orders-on-a-symbol-trade. However, neither this library nor python-binance implement a method to access this endpoint.

**Describe the solution you'd like**
A method to close all the open orders for a symbol. Something like this:
```
    def cancel_orders(self, **params):
        return self._delete('openOrders', True, data=params)
```

**Describe alternatives you've considered**
Closing the orders one by one.. but I'd rather not.

**Additional context**
N/A

**Comment by oliver-zehentleitner** [comment]
Thx, its implemented as `cancel_all_open_orders()`.
