### ISSUE TITLE
FUTURES_COIN_URL seems to be wrong.

### ISSUE THREAD

**Issue by flo-rian** [oliver-zehentleitner/unicorn-binance-rest-api#4]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you using the module on a VPS or other Cloud hosting?
- [ ] Are you using the module on a Raspberry Pi?

#### What kind of internet connection do you have?
```
fiber
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)

#### Options
- [ ] stream_buffer
- [ ] process_stream_data

#### Which endpoint do you connect?
```
 binance.com
```

#### Python Version Requirement
- [x] I am using Python 3.6.1 or above

#### Exact Python Version?
```
Python 3.9.4
```

#### Pip Version?
```
pip 20.2.2
```

#### Dependencies
Run `pip list > pip_list.txt` and upload the file.

#### UNICORN Binance REST API Version?
```
Did you upgrade to the latest release version with `pip install unicorn-binance-rest-api --upgrade`?

Please control what version you are using with this script and post the output: https://github.com/oliver-zehentleitner/unicorn-binance-rest-api/blob/master/tools/get_used_module_version.py
-> the pages results in a 404 ...
```

#### Description of your issue
```
klines = ubra.futures_coin_klines(symbol='ETHUSDT', interval='1m', limit=500)
fails with the URI 

```

**Comment by oliver-zehentleitner** [comment]
Released: https://github.com/oliver-zehentleitner/unicorn-binance-rest-api/releases/tag/1.1.1
